version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - stack.env
    depends_on:
      - db

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - stack.env
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - stack.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 