services:
  pawgress:
    build: .
    ports:
      - "8484:8484"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: wecantliveinamuffin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
